<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Reset filter' => 'Сбросить фильтр',
    'Add spent' => 'Добавить затрату',
    'Refill has been created' => 'Поплнение сохранено',
    'Refills' => 'Пополнения',
    'Spend has been created' => 'Затрата сохранена',
    'Spent' => 'Затрата',
    'Spents' => 'Затраты',
    'Purse' => 'Кошелек',
    'Add refill' => 'Добавить пополнение',
    'Amount' => 'Сумма',
    'Currency' => 'Валюта',
    'Description' => 'Описание',
    'Refill' => 'Пополнение',
    'Refill source' => 'Источник поплнения',
    'Save' => 'Сохранить',
    'Select currency' => 'Выбрать валюту',
    'Current purse value:' => 'Сейчас в кошельке:',


    'New' => 'Новый',
    'Pending' => 'Ожидание',
    'In progress' => 'В процессе',
    'Cancelled' => 'Отмененный',
    'Success' => 'Успех',
    'Fail' => 'Неудача',
    'Select status' => 'Выберите статус',
    'Status' => 'Статус'
];
